package ar.edu.unlam.pb2;

public enum OpcionDeMenu {
	AGREGAR_PROPIEDAD, MODIFICAR_PROPIEDAD,
	AGREGAR_CLIENTE, OBTENER_LISTADO_POR_PRECIO,
	OBTENER_LISTADO_POR_UBICACION, BUSCAR_PROPIEDADES_POR_PRECIO,
	BUSCAR_PROPIEDADES_POR_UBICACION, REALIZAR_VENTA, REALIZAR_ALQUILER, CALCULAR_EL_PRECIO_PROEDIO_DE_LAS_CASAS,SALIR;
}
